version: 1.0.2.{build}
environment:
  matrix:
    - proxy: no_zlog 
      build_args: -p Win32 --skip-unittests --skip-dotnet 
    - proxy: no_zlog_x64
      build_args: -p x64 --skip-unittests --skip-dotnet 
    - proxy: default
      build_args: -p Win32 --use-zlog
    - proxy: default_x64
      build_args: -p x64 --use-zlog
image: Visual Studio 2017
install:
  - git submodule update --init
  - ps: Start-FileDownload 'https://slproweb.com/download/Win32OpenSSL-1_0_2L.exe'
  - cmd /c Win32OpenSSL-1_0_2L.exe /silent /verysilent /sp- /suppressmsgboxes
build:
build_script:
  - bld\build.cmd -c %build_args%
cache:
  - C:\OpenSSL-Win32
matrix:
    fast_finish: true
